# Generated by Django 5.0.1 on 2024-03-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emc_servicerequest',
            old_name='location',
            new_name='state',
        ),
        migrations.AddField(
            model_name='emc_servicerequest',
            name='District',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='emc_servicerequest',
            name='city',
            field=models.CharField(default='unknown', max_length=150),
        ),
    ]
