# Generated by Django 5.0.1 on 2024-04-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_location_emc_servicerequest_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emc_servicerequest',
            name='ip_city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='emc_servicerequest',
            name='ip_contry',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='emc_servicerequest',
            name='ip_ipaddr',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='emc_servicerequest',
            name='ip_lat',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='emc_servicerequest',
            name='ip_lon',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='emc_servicerequest',
            name='ip_regionName',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='emc_servicerequest',
            name='ip_zip',
            field=models.CharField(default='', max_length=150),
        ),
    ]
