# Generated by Django 5.0.1 on 2024-04-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emc_servicerequest_ip_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emc_servicerequest',
            name='state',
        ),
    ]
